# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import square_pb2 as square__pb2


class SquareServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Square = channel.stream_stream(
                '/SquareService/Square',
                request_serializer=square__pb2.Request.SerializeToString,
                response_deserializer=square__pb2.Response.FromString,
                )


class SquareServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Square(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SquareServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Square': grpc.stream_stream_rpc_method_handler(
                    servicer.Square,
                    request_deserializer=square__pb2.Request.FromString,
                    response_serializer=square__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SquareService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SquareService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Square(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/SquareService/Square',
            square__pb2.Request.SerializeToString,
            square__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
