# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import range_generator_pb2 as range__generator__pb2


class RangeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Range = channel.unary_stream(
                '/RangeService/Range',
                request_serializer=range__generator__pb2.Request.SerializeToString,
                response_deserializer=range__generator__pb2.Response.FromString,
                )


class RangeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Range(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Range': grpc.unary_stream_rpc_method_handler(
                    servicer.Range,
                    request_deserializer=range__generator__pb2.Request.FromString,
                    response_serializer=range__generator__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RangeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Range(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/RangeService/Range',
            range__generator__pb2.Request.SerializeToString,
            range__generator__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
